services:
  - type: web
    name: connectorpro-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /healthz
    autoDeploy: true